const ACCESS_TOKEN_LIFTIME = process.env.ACCESS_TOKEN_LIFETIME || 60 * 10
const REFRESH_TOKEN_LIFTIME = process.env.ACCESS_TOKEN_LIFETIME || 60 * 60 * 24

export { ACCESS_TOKEN_LIFTIME, REFRESH_TOKEN_LIFTIME }
